version: 2.1

executors:
  java-8:
    working_directory: ~/build-working-directory
    docker:
      - image: circleci/openjdk:8-jdk
        environment:
          JAVA_OPTS: -XX:+UseG1GC
          # Disable Kotlin compiler daemon - https://discuss.kotlinlang.org/t/solved-disable-kotlin-compiler-process-keepalive/2622
          GRADLE_OPTS: -Dkotlin.compiler.execution.strategy="in-process"
  java-11:
    working_directory: ~/build-working-directory
    docker:
      - image: circleci/openjdk:11-jdk
        environment:
          # Disable Kotlin compiler daemon - https://discuss.kotlinlang.org/t/solved-disable-kotlin-compiler-process-keepalive/2622
          GRADLE_OPTS: -Dkotlin.compiler.execution.strategy="in-process"

commands:
  gradle:
    description: Runs './gradlew' command with the provided cmmand
    parameters:
      command:
        type: string
        default: build
      submit-build-scan:
        type: boolean
        default: false
    steps:
      - run:
          name: Run Gradle Command
          command: ./gradlew << parameters.command >><<# parameters.submit-build-scan >> --scan<</ parameters.submit-build-scan >> --stacktrace
      - store_test_results:
          path: ~/build-working-directory/build/test-results/
  restore-home-cache:
    description: Restores the Gradle home cache.
    steps:
      - run:
          name: Generate cache key
          command: |
            mkdir -p build
            find settings.gradle.kts build.gradle.kts gradle buildSrc/src buildSrc/build.gradle.kts -type f -exec sha256sum '{}' \; | tee build/circle-ci-key.txt
      - restore_cache:
          keys:
            - v2-home-cache-{{ checksum "build/circle-ci-key.txt" }}
            - v2-home-cache-
  save-home-cache:
    description: Saves the Gradle home cache
    steps:
      - run:
          name: Generate cache key
          command: |
            mkdir -p build
            find settings.gradle.kts build.gradle.kts gradle buildSrc/src buildSrc/build.gradle.kts -type f -exec sha256sum '{}' \; | tee build/circle-ci-key.txt
      - save_cache:
          paths:
            - ~/.gradle
          key: v2-home-cache-{{ checksum "build/circle-ci-key.txt" }}
          when: always

jobs:
  test-java-8:
    executor: java-8
    steps:
      - checkout
      - restore-home-cache
      - gradle:
          submit-build-scan: true
      - save-home-cache
      - persist_to_workspace:
          root: ~/build-working-directory
          paths:
            - .gradle/*
            - build/*
            - buildSrc/.gradle/*
            - buildSrc/build/*
  test-java-11:
    executor: java-11
    steps:
      - checkout
      - restore-home-cache
      - attach_workspace:
          at: ~/build-working-directory
      - gradle:
          submit-build-scan: true
  publish:
    executor: java-8
    steps:
      - checkout
      - restore-home-cache
      - attach_workspace:
          at: ~/build-working-directory
      - gradle:
          command: final -P release.useLastTag=true --exclude-task prepare --exclude-task test
      - save-home-cache

workflows:
  version: 2
  build:
    jobs:
      - test-java-8
      - test-java-11:
          requires:
            - test-java-8
      - publish:
          requires:
            - test-java-8
            - test-java-11
          filters:
            tags:
              only: /^\d+\.\d+\.\d+/
          context: BintrayPublish
