name: Release

on:
  create:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  extract_version:
    name: Extract version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.extracted_version.outputs.version }}
    steps:
      - name: Store tag version in output
        id: extracted_version
        run: echo ::set-output name=version::${GITHUB_REF/refs\/tags\//}
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: extract_version
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Gradle wrapper and dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/
            ~/.gradle/caches/wrapper/dists
          key: test-${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle', '**/*.gradle.kts', '**/gradle.properties', 'gradle/**', 'buildSrc/src/main/**') }}
          restore-keys: |
            test-${{ runner.os }}-gradle-
      - name: Gradle Release
        run: |
          ./gradlew --version
          echo "ref=${GITHUB_REF}, command=${GITHUB_REF/refs\/tags\//}"
          ./gradlew final --scan --exclude-task test --warning-mode=all -P "release.version"="${{ needs.extract_version.outputs.version }}" -P "bintray.user"="${{ secrets.BINTRAY_USER }}" -P "bintray.key"="${{ secrets.BINTRAY_KEY }}"
